### ISSUE TITLE
Some functions I use to rotate and persist the image via ImageMagick's convert

### ISSUE THREAD

**Issue by Dima-369** [emacs-eaf/eaf-image-viewer#2]
I just wanted to share this, in case it might be useful, as it certainly is to me!

It uses `convert` from `ImageMagick`.

```emacs-lisp
(defun dima-image-by-convert (file-name degrees-string)
  "Rotate FILE-NAME with the passed DEGREES-STRING.

Note that the file is changed on the file-system."
  ;; redisplay to show the \"Rotating...\" message
  (redisplay)
  (shell-command
   (format "convert '%s' -quality 100 -rotate %s '%s'"
           file-name
           degrees-string
           file-name)))

(defun dima-eaf-image-viewer-rotate-right ()
  (interactive)
  (message "Rotating...")
  (eaf-execute-app-cmd #'eaf-js-proxy-js_rotate_right)
  (let ((degrees "+90"))
    (dima-image-by-convert (eaf-get-path-or-url) degrees)
    (message "Rotated %s and saved to file system" degrees)))

(defun dima-eaf-image-viewer-rotate-left ()
  (interactive)
  (message "Rotating...")
  (eaf-execute-app-cmd #'eaf-js-proxy-js_rotate_left)
  (let ((degrees "-90"))
    (dima-image-by-convert (eaf-get-path-or-url) degrees)
    (message "Rotated %s and saved to file system" degrees)))

(defun dima-eaf-image-viewer-rotate-180 ()
  (interactive)
  (message "Rotating...")
  (eaf-execute-app-cmd #'eaf-js-proxy-js_rotate_right)
  (eaf-execute-app-cmd #'eaf-js-proxy-js_rotate_right)
  (let ((degrees "-180"))
    (dima-image-by-convert (eaf-get-path-or-url) degrees)
    (message "Rotated %s and saved to file system" degrees)))
```

`dima-image-by-convert` is made synchronously so only one image rotation process is run at the time so they don't collide should one spam the keys.

I have also bound those in transient:

```emacs-lisp
(transient-define-prefix dima-transient-eaf-image-viewer ()
  [:class dima-transient-columns
   ["Actions"
    ("r" dima-eaf-image-viewer-rotate-right
     :description "Rotate right and save")
    ("g" dima-eaf-image-viewer-rotate-left
     :description "Rotate left and save")
    ("f" dima-eaf-image-viewer-rotate-180
     :description "Rotate 180 degrees and save")]])
```

Here is a video (note that I also customized the image-viewer UI a little bit):

https://user-images.githubusercontent.com/15002298/146824655-7c93c0d5-4789-44b3-85d2-cf1b09729e5f.mov

**Comment by MatthewZMD** [comment]
Hi, these are definitely useful functions for many people. I'm wondering if you could put it in the EAF [Wiki](https://github.com/emacs-eaf/emacs-application-framework/wiki) section, as it usually has more attention. :-)

**Comment by Dima-369** [comment]
Yeah, sure I can put it in the Wiki but I am unsure where exactly to put it. Should I create a new Wiki page like `image-viewer snippets`?

I know that the Todo List: https://github.com/emacs-eaf/emacs-application-framework/wiki/Todo-List lists this exact thing but I am still unsure where to place my snippet.

**Comment by MatthewZMD** [comment]
Yes, feel free to create a page titled "EAF Image Viewer Snippets"

**Comment by Dima-369** [comment]
Here you go: https://github.com/emacs-eaf/emacs-application-framework/wiki/EAF-Image-Viewer-Snippets

I removed the entry from the Todo List wiki page as well.

**Comment by manateelazycat** [comment]
@Gira-X Thanks for patch, I have push new commit base on your code : https://github.com/emacs-eaf/eaf-image-viewer/commit/d90bf59f722fc3e3594f0eb256094d75f368d238

**Comment by manateelazycat** [comment]
> Here you go: https://github.com/emacs-eaf/emacs-application-framework/wiki/EAF-Image-Viewer-Snippets
> 
> I removed the entry from the Todo List wiki page as well.

I have delete this wiki since rotate file commands have add in eaf-image-viewer, thanks again. ;)

**Comment by Dima-369** [comment]
> I have delete this wiki since rotate file commands have add in eaf-image-viewer, thanks again. ;)

That's even nicer. Great!
